# Release 1.1.0
version: '3.3'
services:
  app:
    image: plumpedboots/camt_converter:latest
    restart: always
    volumes:
      - camt_converter:/app
    ports:
      - 5000:5000
volumes:
   camt_converter:
